# Generated by Django 2.2.7 on 2019-11-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
