# Generated by Django 2.2.7 on 2019-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='city',
        ),
    ]
