# Generated by Django 2.2.5 on 2019-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20191014_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=5),
        ),
    ]
