# Generated by Django 2.2.5 on 2019-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kucun',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='maichu',
            field=models.IntegerField(default=10),
        ),
    ]
