# Generated by Django 2.2.5 on 2019-10-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20191014_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=128)),
                ('phone', models.CharField(default='19983491093', max_length=11)),
            ],
        ),
    ]
