# Generated by Django 3.0.1 on 2020-01-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_choice',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], default=1),
        ),
    ]
