# Generated by Django 2.2.7 on 2019-12-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='sex',
            new_name='gender',
        ),
    ]
