# Generated by Django 3.0.1 on 2020-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=128)),
                ('markdown', models.CharField(max_length=128)),
                ('create_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
