# Generated by Django 2.2.7 on 2019-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
