# Generated by Django 2.2.7 on 2019-11-19 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_persen_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='persen',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 19, 6, 55, 20, 417890, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
